name: Android CI/CD
description: 'Android CI/CD pipeline workflow'
author: 'Henrique Horbovyi <henrikhorbovyi@gmail.com>'
branding:
  icon: 'box'
  color: 'green'

# on:
#   push:
#     branches: 
#      - '*' 
#      - '!master' 
#      - '!release*'
#   pull_request:
#     branches:
#      - '*' 
#      - '!master' 
#      - '!release*'

runs:
  using: 'docker'
  image: 'Dockerfile'
